name: citest
on:
  push:
  pull_request:
jobs:
  test:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get -y update
    - run: sudo apt-get -y install phpunit php-codesniffer
    - uses: actions/checkout@v4
    - run: make citest
